package com.devpt.collapsar.model;

public class ConfigOuterChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.channel_code
     *
     * @mbggenerated
     */
    private Integer channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.daily_max_user_cnt
     *
     * @mbggenerated
     */
    private Integer dailyMaxUserCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_outer_channel.token_expire_period
     *
     * @mbggenerated
     */
    private Integer tokenExpirePeriod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.id
     *
     * @return the value of config_outer_channel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.id
     *
     * @param id the value for config_outer_channel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.gid
     *
     * @return the value of config_outer_channel.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.gid
     *
     * @param gid the value for config_outer_channel.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.create_time
     *
     * @return the value of config_outer_channel.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.create_time
     *
     * @param createTime the value for config_outer_channel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.update_time
     *
     * @return the value of config_outer_channel.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.update_time
     *
     * @param updateTime the value for config_outer_channel.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.is_valid
     *
     * @return the value of config_outer_channel.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.is_valid
     *
     * @param isValid the value for config_outer_channel.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.remark
     *
     * @return the value of config_outer_channel.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.remark
     *
     * @param remark the value for config_outer_channel.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.channel_code
     *
     * @return the value of config_outer_channel.channel_code
     *
     * @mbggenerated
     */
    public Integer getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.channel_code
     *
     * @param channelCode the value for config_outer_channel.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(Integer channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.channel_name
     *
     * @return the value of config_outer_channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.channel_name
     *
     * @param channelName the value for config_outer_channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.daily_max_user_cnt
     *
     * @return the value of config_outer_channel.daily_max_user_cnt
     *
     * @mbggenerated
     */
    public Integer getDailyMaxUserCnt() {
        return dailyMaxUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.daily_max_user_cnt
     *
     * @param dailyMaxUserCnt the value for config_outer_channel.daily_max_user_cnt
     *
     * @mbggenerated
     */
    public void setDailyMaxUserCnt(Integer dailyMaxUserCnt) {
        this.dailyMaxUserCnt = dailyMaxUserCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_outer_channel.token_expire_period
     *
     * @return the value of config_outer_channel.token_expire_period
     *
     * @mbggenerated
     */
    public Integer getTokenExpirePeriod() {
        return tokenExpirePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_outer_channel.token_expire_period
     *
     * @param tokenExpirePeriod the value for config_outer_channel.token_expire_period
     *
     * @mbggenerated
     */
    public void setTokenExpirePeriod(Integer tokenExpirePeriod) {
        this.tokenExpirePeriod = tokenExpirePeriod;
    }
}