package com.devpt.collapsar.model;

public class LogRequestException {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.request_url
     *
     * @mbggenerated
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.post_body
     *
     * @mbggenerated
     */
    private String postBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.enter_time
     *
     * @mbggenerated
     */
    private Integer enterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.error_code
     *
     * @mbggenerated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request_exception.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.id
     *
     * @return the value of log_request_exception.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.id
     *
     * @param id the value for log_request_exception.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.gid
     *
     * @return the value of log_request_exception.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.gid
     *
     * @param gid the value for log_request_exception.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.create_time
     *
     * @return the value of log_request_exception.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.create_time
     *
     * @param createTime the value for log_request_exception.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.update_time
     *
     * @return the value of log_request_exception.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.update_time
     *
     * @param updateTime the value for log_request_exception.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.is_valid
     *
     * @return the value of log_request_exception.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.is_valid
     *
     * @param isValid the value for log_request_exception.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.remark
     *
     * @return the value of log_request_exception.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.remark
     *
     * @param remark the value for log_request_exception.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.request_url
     *
     * @return the value of log_request_exception.request_url
     *
     * @mbggenerated
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.request_url
     *
     * @param requestUrl the value for log_request_exception.request_url
     *
     * @mbggenerated
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.post_body
     *
     * @return the value of log_request_exception.post_body
     *
     * @mbggenerated
     */
    public String getPostBody() {
        return postBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.post_body
     *
     * @param postBody the value for log_request_exception.post_body
     *
     * @mbggenerated
     */
    public void setPostBody(String postBody) {
        this.postBody = postBody == null ? null : postBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.enter_time
     *
     * @return the value of log_request_exception.enter_time
     *
     * @mbggenerated
     */
    public Integer getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.enter_time
     *
     * @param enterTime the value for log_request_exception.enter_time
     *
     * @mbggenerated
     */
    public void setEnterTime(Integer enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.error_code
     *
     * @return the value of log_request_exception.error_code
     *
     * @mbggenerated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.error_code
     *
     * @param errorCode the value for log_request_exception.error_code
     *
     * @mbggenerated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.message
     *
     * @return the value of log_request_exception.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.message
     *
     * @param message the value for log_request_exception.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request_exception.description
     *
     * @return the value of log_request_exception.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request_exception.description
     *
     * @param description the value for log_request_exception.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}