package com.devpt.collapsar.model;

public class RbacGroupRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.group_gid
     *
     * @mbggenerated
     */
    private String groupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_group_role.role_gid
     *
     * @mbggenerated
     */
    private String roleGid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.id
     *
     * @return the value of rbac_group_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.id
     *
     * @param id the value for rbac_group_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.gid
     *
     * @return the value of rbac_group_role.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.gid
     *
     * @param gid the value for rbac_group_role.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.create_time
     *
     * @return the value of rbac_group_role.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.create_time
     *
     * @param createTime the value for rbac_group_role.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.update_time
     *
     * @return the value of rbac_group_role.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.update_time
     *
     * @param updateTime the value for rbac_group_role.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.is_valid
     *
     * @return the value of rbac_group_role.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.is_valid
     *
     * @param isValid the value for rbac_group_role.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.remark
     *
     * @return the value of rbac_group_role.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.remark
     *
     * @param remark the value for rbac_group_role.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.group_gid
     *
     * @return the value of rbac_group_role.group_gid
     *
     * @mbggenerated
     */
    public String getGroupGid() {
        return groupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.group_gid
     *
     * @param groupGid the value for rbac_group_role.group_gid
     *
     * @mbggenerated
     */
    public void setGroupGid(String groupGid) {
        this.groupGid = groupGid == null ? null : groupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_group_role.role_gid
     *
     * @return the value of rbac_group_role.role_gid
     *
     * @mbggenerated
     */
    public String getRoleGid() {
        return roleGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_group_role.role_gid
     *
     * @param roleGid the value for rbac_group_role.role_gid
     *
     * @mbggenerated
     */
    public void setRoleGid(String roleGid) {
        this.roleGid = roleGid == null ? null : roleGid.trim();
    }
}