package com.devpt.collapsar.model;

public class RbacUserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.group_gid
     *
     * @mbggenerated
     */
    private String groupGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_group.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.id
     *
     * @return the value of rbac_user_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.id
     *
     * @param id the value for rbac_user_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.gid
     *
     * @return the value of rbac_user_group.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.gid
     *
     * @param gid the value for rbac_user_group.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.create_time
     *
     * @return the value of rbac_user_group.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.create_time
     *
     * @param createTime the value for rbac_user_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.update_time
     *
     * @return the value of rbac_user_group.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.update_time
     *
     * @param updateTime the value for rbac_user_group.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.is_valid
     *
     * @return the value of rbac_user_group.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.is_valid
     *
     * @param isValid the value for rbac_user_group.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.remark
     *
     * @return the value of rbac_user_group.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.remark
     *
     * @param remark the value for rbac_user_group.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.group_gid
     *
     * @return the value of rbac_user_group.group_gid
     *
     * @mbggenerated
     */
    public String getGroupGid() {
        return groupGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.group_gid
     *
     * @param groupGid the value for rbac_user_group.group_gid
     *
     * @mbggenerated
     */
    public void setGroupGid(String groupGid) {
        this.groupGid = groupGid == null ? null : groupGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_group.user_gid
     *
     * @return the value of rbac_user_group.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_group.user_gid
     *
     * @param userGid the value for rbac_user_group.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }
}