package com.devpt.collapsar.model;

public class UtilRetryTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.context
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.next_time
     *
     * @mbggenerated
     */
    private Integer nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column util_retry_task.retry_num
     *
     * @mbggenerated
     */
    private Integer retryNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.id
     *
     * @return the value of util_retry_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.id
     *
     * @param id the value for util_retry_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.gid
     *
     * @return the value of util_retry_task.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.gid
     *
     * @param gid the value for util_retry_task.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.create_time
     *
     * @return the value of util_retry_task.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.create_time
     *
     * @param createTime the value for util_retry_task.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.update_time
     *
     * @return the value of util_retry_task.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.update_time
     *
     * @param updateTime the value for util_retry_task.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.type
     *
     * @return the value of util_retry_task.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.type
     *
     * @param type the value for util_retry_task.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.status
     *
     * @return the value of util_retry_task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.status
     *
     * @param status the value for util_retry_task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.context
     *
     * @return the value of util_retry_task.context
     *
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.context
     *
     * @param context the value for util_retry_task.context
     *
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.next_time
     *
     * @return the value of util_retry_task.next_time
     *
     * @mbggenerated
     */
    public Integer getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.next_time
     *
     * @param nextTime the value for util_retry_task.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Integer nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column util_retry_task.retry_num
     *
     * @return the value of util_retry_task.retry_num
     *
     * @mbggenerated
     */
    public Integer getRetryNum() {
        return retryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column util_retry_task.retry_num
     *
     * @param retryNum the value for util_retry_task.retry_num
     *
     * @mbggenerated
     */
    public void setRetryNum(Integer retryNum) {
        this.retryNum = retryNum;
    }
}