package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.LogRequestException;
import com.devpt.collapsar.model.LogRequestExceptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogRequestExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int countByExample(LogRequestExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int deleteByExample(LogRequestExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int insert(LogRequestException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int insertSelective(LogRequestException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    List<LogRequestException> selectByExample(LogRequestExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    LogRequestException selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogRequestException record, @Param("example") LogRequestExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogRequestException record, @Param("example") LogRequestExceptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogRequestException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_request_exception
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogRequestException record);
}