package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.RbacGroup;
import com.devpt.collapsar.model.RbacGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RbacGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int countByExample(RbacGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int deleteByExample(RbacGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int insert(RbacGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int insertSelective(RbacGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    List<RbacGroup> selectByExample(RbacGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    RbacGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RbacGroup record, @Param("example") RbacGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RbacGroup record, @Param("example") RbacGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RbacGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RbacGroup record);
}