package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.RbacGroupRole;
import com.devpt.collapsar.model.RbacGroupRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RbacGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int countByExample(RbacGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int deleteByExample(RbacGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int insert(RbacGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int insertSelective(RbacGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    List<RbacGroupRole> selectByExample(RbacGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    RbacGroupRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RbacGroupRole record, @Param("example") RbacGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RbacGroupRole record, @Param("example") RbacGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RbacGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RbacGroupRole record);
}