package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.RbacUserGroup;
import com.devpt.collapsar.model.RbacUserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RbacUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int countByExample(RbacUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int deleteByExample(RbacUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int insert(RbacUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int insertSelective(RbacUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    List<RbacUserGroup> selectByExample(RbacUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    RbacUserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RbacUserGroup record, @Param("example") RbacUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RbacUserGroup record, @Param("example") RbacUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RbacUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RbacUserGroup record);
}