package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.RbacRole;
import com.devpt.collapsar.model.RbacRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RbacRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int countByExample(RbacRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int deleteByExample(RbacRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int insert(RbacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int insertSelective(RbacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    List<RbacRole> selectByExample(RbacRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    RbacRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RbacRole record, @Param("example") RbacRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RbacRole record, @Param("example") RbacRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RbacRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RbacRole record);
}