package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.RbacResource;
import com.devpt.collapsar.model.RbacResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RbacResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int countByExample(RbacResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int deleteByExample(RbacResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int insert(RbacResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int insertSelective(RbacResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    List<RbacResource> selectByExample(RbacResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    RbacResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RbacResource record, @Param("example") RbacResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RbacResource record, @Param("example") RbacResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RbacResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RbacResource record);
}