package com.devpt.collapsar.dao.mapper;

import com.devpt.collapsar.model.UtilAsyncTask;
import com.devpt.collapsar.model.UtilAsyncTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UtilAsyncTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int countByExample(UtilAsyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int deleteByExample(UtilAsyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int insert(UtilAsyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int insertSelective(UtilAsyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    List<UtilAsyncTask> selectByExample(UtilAsyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    UtilAsyncTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UtilAsyncTask record, @Param("example") UtilAsyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UtilAsyncTask record, @Param("example") UtilAsyncTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UtilAsyncTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table util_async_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UtilAsyncTask record);
}